### ISSUE TITLE
Results ignoring max price

### ISSUE THREAD

**Issue by GiorgioMartini** [wpsight/wpcasa-advanced-search#6]
I have wpcasa-advanced-search on my site:  https://buyhouseinmarbella.com/

But when I enter let's say 100000 it returns results with all kinds of prices above and below the specified max.

Any tips on how to fix this? Thanks.

**Comment by codestylist** [comment]
@GiorgioMartini I have tested it on https://demo.wpcasa.com/oslo/ and can not reproduce the issue. It seems you have added some modification of the search form on https://buyhouseinmarbella.com. Please revert them and try it again. Thanks!
